- name: Clone rbenv repo
  git: repo=https://github.com/sstephenson/rbenv.git dest=/home/{{ user }}/.rbenv update=no

- name: Install rbenv plugin
  git: repo=https://github.com/sstephenson/rbenv-vars.git dest=/home/{{ user }}/.rbenv/plugins/rbenv-vars update=no

- name: Install rbenv plugin
  git: repo=https://github.com/sstephenson/ruby-build.git dest=/home/{{ user }}/.rbenv/plugins/ruby-build update=no

- name: Install rbenv plugin
  git: repo=https://github.com/sstephenson/rbenv-default-gems.git dest=/home/{{ user }}/.rbenv/plugins/rbenv-default-gems update=no

- name: Install rbenv plugin
  git: repo=https://github.com/fesplugas/rbenv-installer.git dest=/home/{{ user }}/.rbenv/plugins/rbenv-installer update=no

- name: Install rbenv plugin
  git: repo=https://github.com/rkh/rbenv-update.git dest=/home/{{ user }}/.rbenv/plugins/rbenv-update update=no

- name: Install rbenv plugin
  git: repo=https://github.com/rkh/rbenv-whatis.git dest=/home/{{ user }}/.rbenv/plugins/rbenv-whatis update=no

- name: Install rbenv plugin
  git: repo=https://github.com/rkh/rbenv-use.git dest=/home/{{ user }}/.rbenv/plugins/rbenv-use update=no

- name: Copy rbenv config
  copy: src=rbenv.zsh dest=/home/{{ user }}/.zshrc.d/rbenv.zsh

- name: Copy .gemrc
  copy: src=gemrc dest=/home/{{ user }}/.gemrc

- name: Install packages required for compilation of some stdlib modules
  apt: name={{ item }} state=present
  sudo: true
  with_items:
    - tklib

- name: Install packages required for RubyGems and Rails
  apt: name={{ item }} state=present
  sudo: true
  with_items:
    - zlib1g-dev
    - libssl-dev
    - libreadline-gplv2-dev
    - libmysqlclient-dev
    - libsqlite3-dev

- name: Install packages required for nokogiri
  apt: name={{ item }} state=present
  sudo: true
  with_items:
    - libxml2
    - libxml2-dev
    - libxslt1-dev

- name: Install packages required for imagemagic
  apt: name={{ item }} state=present
  sudo: true
  with_items:
    - imagemagick
    - libmagickwand-dev

- name: Check ruby 2.2.2 installed for system
  shell: zsh -lc 'rbenv versions | grep 2.2.2'
  register: ruby_installed
  changed_when: false
  ignore_errors: yes
  always_run: yes
  environment:
    HOME: /home/tz

- name: Install ruby 2.2.2
  shell: zsh -lc 'rbenv install 2.2.2'
  when: ruby_installed.rc != 0 

- name: Set global ruby 2.2.2
  shell: zsh -lc 'rbenv global 2.2.2'
  when: ruby_installed.rc != 0   

- name: Rbenv rehash
  shell: zsh -lc 'rbenv rehash'
  when: ruby_installed.rc != 0

- name: Install bundler
  shell: zsh -lc 'gem install bundler'
  when: ruby_installed.rc != 0