- name: Install dev soft
  apt: name={{ item }} state=installed
  sudo: true
  with_items:
    - vim
    - exuberant-ctags
    - htop
    - curl
    - ack-grep
    - git
    - git-flow
    - vagrant
    - sphinxsearch
    - openjdk-8-jdk
    - nodejs

- name: Copy .gitconfig
  copy: src=gitconfig dest=/home/{{ user }}/.gitconfig
