- name: Install dev soft
  apt: name={{ item }} state=installed
  become: true
  with_items:
    - vim
    - exuberant-ctags
    - htop
    - curl
    - ack-grep
    - git
    - git-flow
    - meld
    - vagrant
    - openjdk-8-jdk
    - nodejs
    - npm
    - python-setuptools
    - sshfs

- name: Copy .gitconfig
  copy: src=gitconfig dest=/home/{{ user }}/.gitconfig

- name: Copy .vimrc
  copy: src=vimrc dest=/home/{{ user }}/.vimrc

- name: Vundle check directory
  file: path=/home/{{ user }}/.vim/bundle state=directory mode=0755

- name: Install Vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=/home/{{ user }}/.vim/bundle/Vundle.vim update=no
  register: vundle

- name: Install Vundle plugins
  shell: "echo -ne '\n' | vim +PluginInstall +qall"

- name: Install linuxbrew
  git: repo=https://github.com/Homebrew/linuxbrew.git dest=/home/{{ user }}/.linuxbrew update=no

- name: Copy linuxbrew zsh config
  copy: src=linuxbrew.zsh dest=/home/{{ user }}/.zshrc.d/linuxbrew.zsh
