#!/bin/bash
# Source: https://gist.github.com/Saicheg/4231551
################
# Description:
# This script will take screenshot of your desktop
# or only active window ( running with -u param ),
# copy it to /Dropbox/Public/share/ with uniq name
# and save path to clipboard
#################
# Requirements:
# Dropbox
# scrot
# xclip
#################

TSTAMP=`date +%s`
IMAGEPATH=~/Dropbox/tmp/screenshot-$TSTAMP.png
scrot $1 $IMAGEPATH
dropbox sharelink $IMAGEPATH | xclip -selection clipboard
