- name: Install desktop soft
  apt: name={{ item }} state=installed
  become: true
  with_items:
    - chromium-browser
    - filezilla
    - htop
    - iotop
    - keepass2
    - openssh-server
    - skype
    - synaptic
    - terminator
    - guake
    - ubuntu-restricted-extras
    - virtualbox
    - vlc
    - gimp
    - scrot
    - xclip

- name: Copy screenshare to home
  get_url: url=https://gist.githubusercontent.com/iamdeuterium/3366d6005acd489fc49b7f83beda725e/raw/30c02ab952cb4726fe4094995b2a9d1085e79652/screenshare dest=/home/{{ user }}/screenshare mode=0744 force=yes
