- name: Install desktop soft
  apt: name={{ item }} state=installed
  sudo: true
  with_items:
    - chromium-browser
    - filezilla
    - htop
    - keepass2
    - openssh-server
    - skype
    - synaptic
    - terminator
    - ubuntu-restricted-extras
    - virtualbox
    - vlc
